spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Devansh2005@#
    url: jdbc:mysql://localhost:3306/trading
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.gmail.com
    username: Devanshsingla9@gmail.com
    password: kmmz nnlz hxll hyxg
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

application:
  security:
    jwt:
      secret-key: b15f7819606774c89cbc1477c9dcbf149683af67ed2ca3e875718850c39330ce
      expiration: 86400000  # a day
      refresh-token:
        expiration: 604800000  # 7 days
two:
  factor:
    auth:
      otp:
        expiration-minutes: 5