spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: Devansh2005@#
    driver-class-name: com.mysql.cj.jdbc.Driver

application:
  security:
    jwt:
      expiration: 8640000
      secretKey: D86dWrho0Zq0xVv/8bNtBpZEmL5/GV0aul08BuKffepC9RZ8Q4L1nSbPV6J/