spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Devansh2005@#
    url: jdbc:mysql://localhost:3306/users
  output:
    ansi:
      enabled: always

application:
  security:
    jwt:
      secret-key: D86dWrho0Zq0xVv/8bNtBpZEmL5/GV0aul08BuKffepC9RZ8Q4L1nSbPV6J/
      expiration: 86400000  # a day
      refresh-token:
        expiration: 604800000  # 7 days